--SELECT *
--FROM clientes
--ORDER BY QtdePontos DESC
--LIMIT 10


---SELECIONANDO CLIENTES COM TWITCH, MAIS ANTIGO E MAIS PONTOS
SELECT *
FROM clientes
WHERE FlTwitch = 1
ORDER BY DtCriacao ASC, QtdePontos DESC